---
kind: pipeline
type: kubernetes
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.2
  commands:
  - ln -s /var/run/dind/docker.sock /var/run/docker.sock
  - "until (echo | nc local:/var/run/docker.sock | grep -q HTTP); do echo 'waiting for docker.sock'; sleep 2; done"
  - dapper ci
  - ls dist
  volumes:
  - name: docker
    path: /var/run/dind

- name: cache
  image: plugins/s3-cache
  settings:
    pull: false
    rebuild: true
    bucket: edgi-infra-bootstrap
    region: eu-north-1
    debug: true
    mount:
      - dist/artifacts

volumes:
- name: docker
  host:
    path: /var/run/dind
#---
#kind: pipeline
#type: kubernetes
#name: arm64
#
#platform:
#  os: linux
#  arch: arm64
#
#steps:
#- name: build
#  image: rancher/dapper:v0.4.2
#  commands:
#  - ln -s /var/run/dind/docker.sock /var/run/docker.sock
#  - "until (echo | nc local:/var/run/docker.sock | grep -q HTTP); do echo 'waiting for docker.sock'; sleep 2; done"
#  - dapper ci
#  volumes:
#  - name: docker
#    path: /var/run/dind
#
#volumes:
#- name: docker
#  host:
#    path: /var/run/dind
